model = "gpt-5.5"
model_reasoning_effort = "medium"
approval_policy = "on-request"

personality = "pragmatic"

web_search = "cached" # default
# web_search = "disabled"
# web_search = "live"  # same as --search

sandbox_mode = "workspace-write"
[sandbox_workspace_write]
network_access = true
writable_roots = ["/Users/duc.vu/projects/personal", "/Users/duc.vu/configs/"]
exclude_slash_tmp = false
exclude_tmpdir_env_var = false

[projects."/Users/duc.vu/configs"]
trust_level = "trusted"

[projects."/Users/duc.vu/.config/nvim"]
trust_level = "trusted"

[projects."/Users/duc.vu/projects/personal/skills"]
trust_level = "trusted"

[projects."/Users/duc.vu/projects/personal/ai-devkit"]
trust_level = "trusted"

[projects."/Users/duc.vu/projects/personal/raycast-extensions/neovim-launcher"]
trust_level = "trusted"

[projects."/Users/duc.vu/projects/personal"]
trust_level = "trusted"

[projects."/Users/duc.vu/projects/personal/raycast-extensions"]
trust_level = "trusted"

[projects."/Users/duc.vu/projects/personal/codex-plugin-cc"]
trust_level = "trusted"

[projects."/Users/duc.vu/projects/personal/local-agent"]
trust_level = "trusted"

[projects."/Users/duc.vu/projects/personal/agent-to-agent"]
trust_level = "trusted"

[projects."/Users/duc.vu/projects/personal/tmux-agent-picker"]
trust_level = "trusted"

[notice.model_migrations]
"gpt-5.3-codex" = "gpt-5.4"

[features]
hooks = true

[tui]
status_line = ["model-with-reasoning", "project-name", "git-branch", "context-used", "context-window-size", "five-hour-limit", "weekly-limit", "fast-mode"]
theme = "gruvbox-dark"
status_line_use_colors = true

[tui.keymap.editor]
insert_newline = ["ctrl-j", "ctrl-m", "enter", "shift-enter", "alt-enter"]

[tui.model_availability_nux]
"gpt-5.5" = 4

[mcp_servers.openaiDeveloperDocs]
enabled = false
url = "https://developers.openai.com/mcp"

[mcp_servers.openaiDeveloperDocs.tools.search_openai_docs]
approval_mode = "approve"

[mcp_servers.openaiDeveloperDocs.tools.fetch_openai_doc]
approval_mode = "approve"
