model = "gpt-5.4"
model_reasoning_effort = "medium"
approval_policy = "on-request"

personality = "pragmatic"

web_search = "cached" # default
# web_search = "disabled"
# web_search = "live"  # same as --search

sandbox_mode = "workspace-write"
[sandbox_workspace_write]
network_access = true
writable_roots = ["/Users/duc.vu/projects/personal", "/Users/duc.vu/configs/"]
exclude_slash_tmp = false
exclude_tmpdir_env_var = false

[projects."/Users/duc.vu/configs"]
trust_level = "trusted"

[projects."/Users/duc.vu/.config/nvim"]
trust_level = "trusted"

[projects."/Users/duc.vu/projects/personal/skills"]
trust_level = "trusted"

[projects."/Users/duc.vu/projects/personal/ai-devkit"]
trust_level = "trusted"

[projects."/Users/duc.vu/projects/personal/raycast-extensions/neovim-launcher"]
trust_level = "trusted"

[projects."/Users/duc.vu/projects/personal"]
trust_level = "trusted"

[projects."/Users/duc.vu/projects/personal/raycast-extensions"]
trust_level = "trusted"

[projects."/Users/duc.vu/projects/personal/codex-plugin-cc"]
trust_level = "trusted"

[notice.model_migrations]
"gpt-5.3-codex" = "gpt-5.4"

[tui]
status_line = [
  "model-with-reasoning",
  "project-root",
  "git-branch",
  "context-remaining",
  "context-window-size",
  "five-hour-limit",
  "weekly-limit",
]
