# prefix
set -g prefix C-a
unbind C-b
bind C-a send-prefix

set -g mouse on
set -g focus-events on
# set -g focus-follows-mouse on

# smart split pane
bind-key -n C-Enter if-shell -F '#{e|>|:#{e|*|:#{pane_height},#{window_cell_height}},#{e|*|:#{pane_width},#{window_cell_width}}}' \
	'split-window -v -c "#{pane_current_path}"' \
	'split-window -h -c "#{pane_current_path}"'

bind '"' split-window -c "#{pane_current_path}"
bind % split-window -hc "#{pane_current_path}"

# pane resize
bind r switch-client -T resize-mode
bind-key -T resize-mode -r h resize-pane -L 10
bind-key -T resize-mode -r j resize-pane -D 10
bind-key -T resize-mode -r k resize-pane -U 10
bind-key -T resize-mode -r l resize-pane -R 10
bind-key -T resize-mode -r Left resize-pane -L 10
bind-key -T resize-mode -r Down resize-pane -D 10
bind-key -T resize-mode -r Up resize-pane -U 10
bind-key -T resize-mode -r Right resize-pane -R 10

# pane navigation
bind-key -n C-h select-pane -L
bind-key -n C-j select-pane -D
bind-key -n C-k select-pane -U
bind-key -n C-l select-pane -R

bind-key -n C-t new-window -c "#{pane_current_path}"

bind X kill-pane
