# prefix
set -g prefix C-a
unbind C-b
bind C-a send-prefix

set -g mode-keys vi
set -g mouse on
set -g focus-events on
set -g history-limit 10000
# set -g focus-follows-mouse on
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

set -s extended-keys on
set -as terminal-features 'xterm*:extkeys,xterm-ghostty:hyperlinks'

set -g pane-border-indicators off
set -g pane-border-status off
set -g pane-border-lines single
set -g pane-border-style fg=black,bright
set -g pane-active-border-style fg=cyan

set -g popup-border-lines single
set -g popup-border-style fg=cyan
