# prefix
set -g prefix C-a
unbind C-b
bind C-a send-prefix

set -g mode-keys vi
set -g mouse on
set -g focus-events on
# set -g focus-follows-mouse on
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

set -s extended-keys on
set -as terminal-features 'xterm*:extkeys'
