set -g @plugin 'vaduc079/tmux-agent-picker'
set -g @agent-picker-key "C-a"
set -g @agent-picker-status-width "12"
set -g @agent-picker-agent-width "8"
set -g @agent-picker-popup-width "90%"
set -g @agent-picker-popup-height "90%"

