set -g @plugin 'vaduc079/tmux-agent-picker'
set -g @agent-picker-key "C-a"
set -g @agent-picker-status-width "12"
set -g @agent-picker-agent-width "8"
set -g @agent-picker-title-width "35"
set -g @agent-picker-cwd-width "33"
set -g @agent-picker-tmux-width "22"

