set -g automatic-rename on
# Auto-rename windows as:
# - /<cwd basename> for shells
# - nvim:<cwd basename> for Neovim
# - <program>:<pane title> for other programs with a non-hostname pane title
# - <program> otherwise
set -g automatic-rename-format '#{?#{m/r:^(bash|fish|ksh|nu|sh|zsh)$,#{pane_current_command}},/#{b:pane_current_path},#{?#{m:nvim,#{pane_current_command}},#{pane_current_command}:#{b:pane_current_path},#{?#{&&:#{pane_title},#{!:#{||:#{m:#{host},#{pane_title}},#{m:#{host_short},#{pane_title}}}}},#{pane_current_command}:#{pane_title},#{pane_current_command}}}}'

set -g status-left ""

set -g window-status-format "[#I#F] #{=50:window_name}"
set -g window-status-current-format " [#I#F] #{=50:window_name} "

set -g @status_right_window_offset "#[fg=#665c54#,bg=default]#[fg=#ebdbb2#,bg=#665c54] #{window_offset_x}#,#{window_offset_y} #[fg=#fabd2f#,bg=#665c54]"
set -g @status_right_zoom '#{?window_zoomed_flag,#[fg=#fabd2f#,bg=default]#[fg=#282828#,bg=#fabd2f]  zoomed #[fg=#458588#,bg=#fabd2f],#[fg=#458588#,bg=default]}'
set -g @status_right_key_table "#[fg=#282828,bg=#458588] #{client_key_table} "
set -g @status_right_session "#[fg=#a89984,bg=#458588]#[fg=#282828,bg=#a89984] #{session_name} "
set -g status-right "#{?window_bigger,#{E:@status_right_window_offset},}#{E:@status_right_zoom}#{E:@status_right_key_table}#{E:@status_right_session}"

set -g status-justify left
set -g status-style "fg=#ebdbb2,bg=default"
set -g status-left-style "fg=#ebdbb2,bg=default"
set -g status-right-style "fg=#a89984,bg=default"
set -g message-style "fg=#ebdbb2,bg=#665c54"
set -g mode-style "fg=#282828,bg=#fabd2f"
set -g window-status-style "fg=#928374,bg=default"
set -g window-status-current-style "fg=#282828,bg=#83a598"
set -g window-status-activity-style "fg=#b8bb26,bg=default"
set -g window-status-bell-style "fg=#fb4934,bg=default"
