source-file ~/.config/tmux/global-options.conf
source-file ~/.config/tmux/status-line.conf
source-file ~/.config/tmux/key-bindings.conf

source-file ~/.config/tmux/plugins.conf
# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
set-environment -g PATH "/opt/homebrew/bin:/bin:/usr/bin"
set-environment -g TMUX_PLUGIN_MANAGER_PATH "$HOME/.tmux/plugins/"
run '~/.tmux/plugins/tpm/tpm'
