gui:
  nerdFontsVersion: "3"
os:
  openLink: open "$(echo {{link}} | sed 's/%2F/\//g')"
  editPreset: "vscode"
git:
  overrideGpg: true
  pagers:
    - colorArg: always
      pager: delta --dark --syntax-theme=gruvbox-dark --paging=never --line-numbers --true-color=always --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
